name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.js суулгах
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Dependecies суулгах
        run: npm CI

      - name: Тест ажиллуулах
        run: npm test
